<!--附件様版-->
<script type="text/html" id="tabbr_remark1_1">
	<table border="0" class="bluetable" cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="sfont9" colspan="7">商標圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="sfont9" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt11_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr style="display:none">
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="sfont9" colspan="7">大陸地區之自然人或法人之身分證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="sfont9" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt11_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="sfont9" colspan="7">委任書(<input TYPE="checkbox" NAME="tt11_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt11_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt11_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_5">
	<TABLE border="0" class="bluetable" cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt51_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt51_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地團體商標者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt51_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tt51_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tt51_Z8C" value="Z8C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt51_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt51_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_D">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttd1_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="ttd1_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人、團體或政府機關證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人得為證明之資格或能力之文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地證明標章者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttd1_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="ttd1_Z6C" value="Z6C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="ttd1_Z8C" value="Z8C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人不從事所證明商品之製造、行銷或服務提供之聲明。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttd1_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttd1_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_9">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt91_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt91_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tt91_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tt91_Z6C" value="Z6C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
		</tr>
		<tr>
			<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt91_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
			<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt91_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
		</tr>
	</table>
</script>
<!------->
<script type="text/html" id="tabbr_remark1_2">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt22_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr style="display:none">
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">大陸地區之自然人或法人之身分證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt22_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt22_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt22_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt22_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_6">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt62_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt62_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地團體商標者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt62_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tt62_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tt62_Z8C" value="Z8C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt62_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt62_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_A">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tta2_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tta2_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tta2_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z61" value="Z61" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tta2_Z61C" value="Z61C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tta2_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tta2_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_E">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tte2_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tte2_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人、團體或政府機關證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人得為證明之資格或能力之文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地證明標章者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tte2_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tte2_Z6C" value="Z6C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z81" value="Z81" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tte2_Z81C" value="Z81C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人不從事所證明商品之製造、行銷或服務提供之聲明。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tte2_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tte2_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>
<!------->
<script type="text/html" id="tabbr_remark1_3">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。（商標圖樣非以五線譜、簡譜表示者，免貼圖）</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">載有本件聲音之.wav檔光碟片。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt33_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr style="display:none">
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">大陸地區之自然人或法人之身分證明文件。</td>
	</tr>
	<tr >
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt33_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt33_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt33_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt33_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_7">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。（商標圖樣非以五線譜、簡譜表示者，免貼圖）</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">載有本件聲音之.wav檔光碟片。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt73_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr >
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt73_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地團體商標者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt73_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tt73_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tt73_Z8C" value="Z8C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt73_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt73_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_B">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。（標章圖樣非以五線譜、簡譜表示者，免貼圖）</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">載有本件聲音標章之.wav檔光碟片。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttb3_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttb3_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="ttb3_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z61" value="Z61" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="ttb3_Z61C" value="Z61C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttb3_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttb3_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_F">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">標章圖樣浮貼一式5張。（標章圖樣非以五線譜、簡譜表示者，免貼圖）</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z10" value="Z10" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">載有本件聲音標章之.wav檔光碟片。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttf3_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr >
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="ttf3_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人、團體或政府機關證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人得為證明之資格或能力之文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地證明標章者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttf3_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="ttf3_Z6C" value="Z6C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z81" value="Z81" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="ttf3_Z81C" value="Z81C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人不從事所證明商品之製造、行銷或服務提供之聲明。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttf3_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttf3_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>
<!------->
<script type="text/html" id="tabbr_remark1_4">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別視圖各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt44_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr style="display:none">
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">大陸地區之自然人或法人之身分證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt44_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt44_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">不具功能性之證據資料。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt44_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt44_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_8">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別視圖各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tt84_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tt84_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地團體商標者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tt84_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="tt84_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="tt84_Z8C" value="Z8C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">不具功能性之證據資料。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tt84_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tt84_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_C">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別視圖各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttc4_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人資格證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttc4_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="ttc4_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z61" value="Z61" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="ttc4_Z61C" value="Z61C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttc4_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttc4_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_G">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別視圖各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttg4_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="ttg4_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z3" value="Z3" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">法人、團體或政府機關證明文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人得為證明之資格或能力之文件。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z51" value="Z51" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人具代表性證明文件(申請產地證明標章者始需檢附)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttg4_Z5C" value="Z5C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z6" value="Z6" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書(<input TYPE="checkbox" NAME="ttg4_Z6C" value="Z6C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z81" value="Z81" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">使用規範書之電子檔光碟片(<input TYPE="checkbox" NAME="ttg4_Z81C" value="Z81C" onclick="br_form.CopyStr()">附中文譯本或應記載事項之中文節譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z7" value="Z7" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">申請人不從事所證明商品之製造、行銷或服務提供之聲明。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z8" value="Z8" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttg4_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttg4_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
			
	</tr>
	</table>
</script>
		
<script type="text/html" id="tabbr_remark1_I">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別視圖各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z21" value="Z21" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標樣本。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="tti4_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="tti4_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="tti4_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="tti4_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="tti4_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_J">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">個別圖像各浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z21" value="Z21" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">存載動態商標之AVI或MPEG檔光碟片。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttj4_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="ttj4_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttj4_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttj4_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttj4_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

<script type="text/html" id="tabbr_remark1_K">
	<TABLE border="0" class="bluetable"  cellspacing="1" cellpadding="2" width="100%">
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z1" value="Z1" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標圖樣浮貼一式5張。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z21" value="Z21" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">商標樣本。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z2" value="Z2" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">優先權證明文件(<input TYPE="checkbox" NAME="ttk4_Z2C" value="Z2C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
		
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z31" value="Z31" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">展覽會優先權證明文件(<input TYPE="checkbox" NAME="ttk4_Z31C" value="Z31C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z4" value="Z4" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">委任書(<input TYPE="checkbox" NAME="ttk4_Z4C" value="Z4C" onclick="br_form.CopyStr()">附中文譯本)。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z5" value="Z5" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">已取得識別性之具體事證。</td>
	</tr>
	<tr>
		<td class="lightbluetable" align="right"><input TYPE="checkbox" NAME="ttk4_Z9" value="Z9" onclick="br_form.CopyStr()"></td>
		<td class="whitetablebg" colspan="7">其他證明文件。<input TYPE="text" NAME="ttk4_Z9t" SIZE="50" onchange="br_form.CopyStr()"></td>
	</tr>
	</table>
</script>

